TEAM_ID_NAME_MAP = {
    "Bitches and Hoes": 0,
    "Wolves": 1,
    "Condacorp": 2,
    "Yodiegang": 3,
    "Futas": 4,
    "Binturong": 5,
    "Ballers": 6,
    "Predators": 7,
    "Bears": 8,
    "Gooners": 9,
    "NR": 10,
    "Crows": 11,
    "Ball Breakers": 12,
    "Kiwis": 13,
    "Figgers": 14,
    "Niners": 15,
    "Missiles": 16,
}
